repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: tflint
        args:
          - "--module"
          - "--deep"
          - "--config=.tflint.hcl"
      - id: terraform-validate
      - id: terraform-fmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.0
    hooks:
      - id: terraform_tfsec
      - id: terraform_docs
      - id: checkov